config/routes.rb
Rails.application.routes.draw do
  resources :authors
  resources :books
  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  root "authors#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_and_belongs_to_many :books

  validates :first_name, :last_name, :presence => true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category
  has_and_belongs_to_many :authors

  validates :title, :presence => true, :uniqueness => true
  # El título del libro no puede ser nulo y debe ser único.
  validates :description, :presence => true
  # La descripción del libro no puede ser nula.
  def is_new
    created_at.today? ? "new!" : ""
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books

  validates :name, :presence => true, :uniqueness => true
  validates :abbreviation, length: {minimum: 3}, allow_blank: true
  # El mínimo de la abreviación debe ser de 3 caracteres.
  # Se puede dejar en blanco.


  # validates :abbreviation, length: {maximum: 500} -> MAX
  # validates :abbreviation, length: {in: 6..20} -> ENTRE
  # validates: abbreviation, length: {is: 6} -> EXACTO
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  http_basic_authenticate_with name: "admin", password: "admin", except: [:index, :show]
end
# está puesto para que aparezca lo del logueo en el caso de querer crear un libro

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show edit update destroy ]

  # GET /authors or /authors.json
  def index
    session[:user_logged] = "Rafael Santos Borré"
    #las sesiones no tienen nada hasta que yo las pongo.
    @authors = Author.all
    @authors = @authors.order(params[:by] + " " + params[:order]) if params[:sort] == "true"
  end

  # GET /authors/1 or /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors or /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: "Author was successfully created." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1 or /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: "Author was successfully updated." }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1 or /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: "Author was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:first_name, :last_name)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
    @books = @books.where(:category_id => params[:category_id]) if params[:category_id]
    # junto con el index de categories es para que muestre los libros que pertenecen a dicha categoría.
    @books = @books.joins(:authors).where(:authors => {:id => params[:author_id]}) if params[:author_id]
    # Mostrar los libros escritos que escribió el autor que elegimos DESDE autor.
    @books = @books.order(params[:by] + " " + params[:order]) if params[:sort] == "true"
    # orden de libros + el orden del index.
    @books = @books.where(["title LIKE :filter", :filter => ("%" + params[:filter] + "%")]) unless params[:filter].blank?
# buscador de libros según título.
    # @books = @books.where(["category_id LIKE :filter2", :filter2 => ("%" + params[:filter2] + "%")]) unless params[:filter2].blank?
    @books = @books.where(:category_id => params[:category_id]) if params[:category_id]
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :description, :category_id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
    @categories = @categories.joins(:books).where(:books => {:id => params[:book_id]}) if params[:book_id]
    @categories = @categories.order(params[:by] + " " + params[:order]) if params[:sort] == "true"
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :abbreviation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th><%= link_to "First name", authors_path(:sort => true, :by => "first_name", :order => (params[:order] == "asc" ? "desc" : "asc")) %></th>
      <th><%= link_to "Last name", authors_path(:sort => true, :by => "last_name", :order => (params[:order] == "asc" ? "desc" : "asc")) %></th>
      <th>Libros</th>
      <!-- va a saber cómo ordennarlos gracias al :by -->
      <!-- consulta qué tiene ese parámetro y si tiene asc, entonces lo cambia a desc-->
      <!-- si el parámetro es desc ponele asc-->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.first_name %></td>
        <td><%= author.last_name %></td>
        <td>
          <% if author.books.count == 0 %>
          <%# Si el autor no escribió ningún libro que muestre 0 %>
          <%= author.books.count %>
          <% else %>
          <%# sino, que me ponga un link que me lleve hasta los libros %>
          <%= link_to author.books.count, books_path(:author_id => author.id) %>
          <% end %>
        </td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @author.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @author.last_name %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%#= form.text_field :category_id %>
    <%= form.collection_select( :category_id, Category.all, :id, :name)  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<form method="GET" action="/books">
  Título: <input type="text" name="filter" />
  <input type="submit">
</form><br>
<!-- Esto sirve para poner un buscador (como filtro) en 'Libros' -->
<form method="GET" action="/categories">
  Categoría: <select name="category_id">
    <%= Category.all.each do | c | %>
    <option value= "<%= c.id %>"> <%=c.name %> </option>
    <% end %>
    </select>
</form><br>


<table>
  <thead>
    <tr>
      <th><%= link_to "Title", books_path(:sort => true, :by => "title", :order => (params[:order] == "asc" ? "desc" : "asc")) %></th>
      <th>Description</th>
      <th>Categoría</th>
      <th>Autores</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.description %></td>

        <td>
          <%= link_to book.category_id, categories_path(:book_id => book.id) %>
        </td>

        <td>
          <% if book.authors.count == 0 %>
          <%# Si el libro no fue escrito por ningún autor que muestre 0 %>
          <%= book.authors.count %>
          <% else %>
          <%# sino, que me ponga un link que me lleve hasta los autores %>
          <%= link_to book.authors.count, authors_path(:book_id => book.id) %>
          <% end %>
        </td>

        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>Category:</strong>
  <%#= @book.category_id %>
  <%= @book.category.name unless @book.category.nil? %>
  <%# nos dice que no va a aparecer nada si el la categoría del libro es nula %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :abbreviation %>
    <%= form.text_field :abbreviation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th><%= link_to "Name", categories_path(:sort => true, :by =>"name", :order => (params[:order] == "asc" ? "desc" : "asc")) %></th>
      <th>Abbreviation</th>
      <th>Cantidad de libros</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.abbreviation %></td>
        <td><%= link_to category.books.count, books_path(:category_id => category.id) %></td>
        <!-- junto con el books_controller es para ver los libros que pertenecen a dicha categoría -->
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Abbreviation:</strong>
  <%= @category.abbreviation %>
</p>

<p>
  <strong>Libros de esta categoría:</strong>
  <%= @category.books.count %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "Autores", authors_path %> |
    <%= link_to "Libros", books_path %> |
    <%= link_to "Categorías", categories_path %> <br>
    <!-- <strong>Usuario logueado:</strong> <%= session[:user_logged] %><br><br> -->
    <%= yield %>
  </body>
</html>